if __name__ == "__main__":
	import pandas as pd
	data = pd.read_csv("data/CRDC2013_14.csv", encoding="Latin-1")
	data["total_enrollment"] = data["TOT_ENR_M"] + data["TOT_ENR_F"]
	all_enrollment =  data["total_enrollment"].sum()
	SCH_ENR_HI_M = data["SCH_ENR_HI_M"].sum()
	SCH_ENR_HI_F = data["SCH_ENR_HI_F"].sum()
	SCH_ENR_AM_M = data["SCH_ENR_AM_M"].sum()
	SCH_ENR_AM_F = data["SCH_ENR_AM_F"].sum()
	SCH_ENR_AS_M = data["SCH_ENR_AS_M"].sum()
	SCH_ENR_AS_F = data["SCH_ENR_AS_F"].sum()
	SCH_ENR_HP_M = data["SCH_ENR_HP_M"].sum()
	SCH_ENR_HP_F = data["SCH_ENR_HP_F"].sum()
	SCH_ENR_BL_M = data["SCH_ENR_BL_M"].sum()
	SCH_ENR_BL_F = data["SCH_ENR_BL_F"].sum()
	SCH_ENR_WH_M = data["SCH_ENR_WH_M"].sum()
	SCH_ENR_WH_F = data["SCH_ENR_WH_F"].sum()
	SCH_ENR_TR_M = data["SCH_ENR_TR_M"].sum()
	SCH_ENR_TR_F = data["SCH_ENR_TR_F"].sum()
	print("Hispanic Male: ", SCH_ENR_HI_M/all_enrollment)
	print("Hispanic Female: ", SCH_ENR_HI_F/all_enrollment)
	print("American Indian Male: ", SCH_ENR_AM_M/all_enrollment)
	print("American Indian Female: ", SCH_ENR_AM_F/all_enrollment)
	print("Asian Male: ", SCH_ENR_AS_M/all_enrollment)
	print("Asian Female: ", SCH_ENR_AS_F/all_enrollment)
	print("Hawaiian or Pacific Islander: ", SCH_ENR_HP_M/all_enrollment)
	print("Hawaiian or Pacific Islander: ", SCH_ENR_HP_F/all_enrollment)
	print("Black Male: ", SCH_ENR_BL_M/all_enrollment)
	print("Black Female: ", SCH_ENR_BL_F/all_enrollment)
	print("White Male: ", SCH_ENR_WH_M/all_enrollment)
	print("White Female: ", SCH_ENR_WH_F/all_enrollment)
	print("Two or more races Male: ", SCH_ENR_TR_M/all_enrollment)
	print("Two or more races Female: ", SCH_ENR_TR_F/all_enrollment)

